CREATE TABLE STUDENTS( Id INTEGER, Stud_name TEXT, Marks INTEGER);
INSERT INTO STUDENTS VALUES
(1, 'Aditya', 95),
(2, 'Kapil', 80),
(3, 'Yash', 74);
SELECT * FROM STUDENTS;

SELECT * FROM STUDENTS WHERE Marks > 75;

SELECT * FROM STUDENTS ORDER BY Marks DESC;

UPDATE STUDENTS SET Marks = 90 WHERE Stud_name = 'Yash';
SELECT * FROM STUDENTS;